[package]
name = "bearpswmng"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.27"
log4rs = "1.4.0-rc2"
home = "0.5.11"
clap = { version = "^4.5.45", features = ["derive"] }
orion = "0.17.11"
rand = "0.9.2"
base64 = "0.22.1"


rand_core = { version = "=0.9.3", features = ["os_rng"]}