refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d} [{f}:{L}] {m}{n}"
  requests:
    kind: rolling_file
    path: "log/trace.log"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 10mb   # rotate when log exceeds 10 MB
      roller:
        kind: fixed_window
        pattern: "log/trace.log.{}"
        base: 1
        count: 5      # keep 5 old log files
    encoder:
      pattern: "{d} [{f}:{L}] {m}{n}"
root:
  level: trace
  appenders:
    - stdout
    - requests
loggers:
  app::backend::db:
    level: trace
  app::requests:
    level: trace
    appenders:
      - requests
    additive: true
