#ifndef BEARPSWMNG_VERSION_H
#define BEARPSWMNG_VERSION_H

#define MAJOR_VERSION 1
#define MINOR_VERSION 0
#define BUILD_NUMBER 0
#define BUILD_DATE "01.05.2024"

#endif /* BEARPSWMNG_VERSION_H */ 